---
swagger: "2.0"
info:
  description: "Patient API"
  version: "1.0.0"
  title: "Patient API"
host: "localhost:3001"
basePath: "/api"
tags:
- name: "patient"
  description: "Everything about patient"
schemes:
- "http"
paths:
  /patient/{shrId}:
    get:
      summary: "Find patient by SHR ID"
      description: "Returns a single patient record"
      operationId: "getPatientById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "shrId"
        in: "path"
        description: "ID of patient to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
        400:
          description: "Invalid ID supplied"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
        404:
          description: "Patient not found"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
              description: "Setting this header to `*` allows all origins. This is\
                \ handy for public REST APIs that don't require authentication. But,\
                \ according to the HTTP spec, browsers *WILL NOT* send cookies if\
                \ this header is `*`, regardless of what you set `Access-Control-Allow-Credentials`\
                \ to.\n"
              default: "*"
      x-swagger-router-controller: "Default"
definitions: {}
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
